# Generated by Django 5.0.6 on 2026-06-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_user_expense_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code (e.g., USD, EUR, GBP)', max_length=3, null=True),
        ),
    ]
