# Generated by Django 5.0.6 on 2026-06-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly spending limit for this category', max_digits=10, null=True),
        ),
    ]
